{{- if .Values.services }}

{{- $services := .Values.services }}
{{- range $index, $service := $services }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $service.namespace }}

spec:
  selector:
    app: {{ $.Release.Name }}

  ports:
  {{- range $index, $port := $service.ports }}
  - name: {{ $port.name }}
    port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
    protocol: {{ $port.protocol }}
  {{- end }}
---

{{- end }}
{{- end }}