apiVersion: v1
kind: Secret
metadata:
  name: macbook-admin-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: macbook-admin
type: kubernetes.io/service-account-token