apiVersion: apps/v1
kind: Deployment
metadata:
  name: birchwood-server
  namespace: server
  labels:
    app: birchwood-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birchwood-server
  template:
    metadata:
      labels:
        app: birchwood-server
    spec:
      containers:
      - name: birchwood-server
        image: birchwood-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173

