apiVersion: v1
kind: Service
metadata:
  name: birchwood-server
  namespace: server
spec:
  selector:
    app: birchwood-server
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 8000
  type: ClusterIP
