# apiVersion: v1
# kind: Service
# metadata:
#   name: birchwood-backend
#   namespace: backend
# spec:
#   selector:
#     app: birchwood-backend
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80 
#       targetPort: 8000
#   type: ClusterIP
