common-values:
  replicaCount: 1
  namespace: birchwood

  image:
    repository: 192.168.1.126:5000/
    name: birchwood-backend
    pullPolicy: IfNotPresent
    tag: "latest"

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000