gateway: 
  name: istio-gateway-ingress

  
  # Override the injection settings in the template
  podAnnotations:
    inject.istio.io/templates: gateway
    sidecar.istio.io/inject: "true"
  
  labels:
    istio: ingressgateway
    sidecar.istio.io/inject: "true"

  service:
    ports:
    - name: http2
      port: 80
      protocol: TCP 
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  