gateway: 
  sidecarInjectorWebhook:
    enabled: false
  injectionTemplate: ""
  annotations:
    sidecar.istio.io/inject: "false"
  # env:
  #   MALLOC_CONF: "background_thread:true,metadata_thp:\"auto\",dirty_decay_ms:30000,muzzy_decay_ms:30000"
  #   TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES: "134217728"
  #   GODEBUG: "madvdontneed=1"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 1Gi
  image:
    repository: docker.io/istio/proxyv2
    tag: "1.24.2-distroless-arm64"
    pullPolicy: IfNotPresent
  service:
    ports:
    - name: http2
      port: 80
      protocol: TCP 
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443

  labels:
    istio: ingressgateway
    sidecar.istio.io/inject: "false"

  