apiVersion: v1
kind: ConfigMap
metadata:
  name: birchwood-blog-app-config
  namespace: blog
data:
  appConfig.js:
  {{ with .Values.common }} |
  module.exports = {
    birchwoodServiceUrl: "{{ .birchwoodServiceUrl }}",
    msg: "config map!",
    
  }