---
- name: Test Ansible Connection
  hosts: raspberry_pis
  gather_facts: true
  tasks:
    - name: Print system information
      debug:
        msg: "Hello from {{ inventory_hostname }}! OS: {{ ansible_distribution }} {{ ansible_distribution_version }}" 