apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata: 
  name: default
  namespace: istio-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.k8s.birchwood.lol'
    port:
      name: http
      number: 80
      protocol: HTTP